language: cpp
compiler:
    - gcc
    - clang
branches:
  except:
    - master
    - feature-travis-debianpkg
notifications:
  email:
    - reports@islog.com
    - ryp.sqrt@gmail.com
before_install:
    - sudo add-apt-repository -y "deb http://fr.archive.ubuntu.com/ubuntu/ trusty main" # NOTE use ubuntu trusty repo instead of hacking with custom user packages
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq g++ clang cmake
    - sudo apt-get install -qq libtclap-dev libboost-dev valgrind
    - sudo apt-get install -qq libgtest-dev
    #  NOTE gtest install workaround
    - pushd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libgtest* /usr/lib/
    - popd
    # -- workaround end
before_script:
	## Manually build libpifacedigital and libmcp23s17
    - pushd libpifacedigital; make; popd;
    - pushd libmcp23s17; make; popd;
    - mkdir build && pushd build
script:
    - if [ ${COVERITY_SCAN_BRANCH} != 1 ] ; then cmake .. -DCMAKE_BUILD_TYPE=Debug -DLEOSAC_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/usr -DLEOSAC_PLATFORM=Travis ; fi
    - if [ ${COVERITY_SCAN_BRANCH} != 1 ] ; then make ; fi
after_success:
    - sudo make install
    - ctest --output-on-failure
    - valgrind --leak-check=full --show-reachable=yes --suppressions=../valgrind/leosac-travis.supp ./leosac -t -g cfg/hardwareDebug.xml -f cfg/defaultDebug.xml
deploy:
  edge: true
  provider: releases
  api-key:
    - secure: bNT1ZzHXLr+WF92XtjBVMkjR+r39RtGbKndyIcKj5nralHCSzYH+6y2QBydj3AGJ5KwldDYJuCh18EeXH+Rl9udqrFQptwBcMYW7B0S4fTxQMZu+z6wNSWxvoDeCN3iR86UfcmVtivv1tsQSNqWWQPz+tmjwNrceqPcG9kzS8KM=
  file: "$LEOSAC_DEB"
  on:
    repo: islog/leosac
    tags: true
    all_branches: true
before_deploy:
    - sudo apt-get install -qq build-essential dh-make dpkg-dev debhelper devscripts
    - PRISTINE_ARCHIVE=${TRAVIS_TAG}.tar.gz
    - wget https://github.com/islog/leosac/archive/${PRISTINE_ARCHIVE}
    - tar -xf ${PRISTINE_ARCHIVE}
    - mv ${PRISTINE_ARCHIVE} leosac_${TRAVIS_TAG}.orig.tar.gz
    - pushd leosac-${TRAVIS_TAG}
    - bash scripts/travis_makepkg.sh
    - popd
    - LEOSAC_DEB="`find * -maxdepth 0 -name leosac_*.deb`"
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EW8MSkUc99OH4F9y/k8qZb1pzLx+UQRNl7JY4X57SXx6TWhYj9ufnddsS8md4yydU2m6vhW2o16lYOh/0EqMFB0+zj/5syc+gDprhQ7ahaECdBCqVQT9zB5PqGWE+Sv1JkZQ2eHBYEJhHnC7NXKcVEqT+N8O320m5mdWqfdA4Hs="

addons:
  coverity_scan:
    project:
      name: "islog/leosac"
      description: "Build submitted via Travis CI"
    notification_email: kapp.arno@gmail.com
    build_command_prepend: "cmake .. -DCMAKE_BUILD_TYPE=Debug -DLEOSAC_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/usr -DLEOSAC_PLATFORM=Travis"
    build_command:   "make"
    branch_pattern: develop
