language: cpp
compiler:
    - gcc
    - clang
branches:
  except:
    - master
notifications:
  email:
    - reports@islog.com
    - ryp.sqrt@gmail.com
before_install:
    - sudo add-apt-repository -y "deb http://fr.archive.ubuntu.com/ubuntu/ trusty main" # NOTE use ubuntu trusty repo instead of hacking with custom user packages
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq g++ clang cmake
    - sudo apt-get install -qq libtclap-dev libboost-dev valgrind
    - sudo apt-get install -qq build-essential dh-make dpkg-dev debhelper devscripts  # Deb Packaging
    - sudo apt-get install -qq libgtest-dev
    #  NOTE gtest install workaround
    - pushd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo mv libgtest* /usr/lib/
    - popd
    # -- workaround end
before_script:
    - mkdir build && pushd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DLEOSAC_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=/usr -DLEOSAC_PLATFORM=Travis
script:
    - make
after_success:
    # NOTE create fake package
    - sudo make install
    - ctest --output-on-failure
    - valgrind --leak-check=full --show-reachable=yes --suppressions=../valgrind/leosac-travis.supp ./leosac -t -g cfg/hardwareDebug.xml -f cfg/defaultDebug.xml
deploy:
  edge: true
  provider: releases
  skip_cleanup: true
  api-key:
    - secure: bNT1ZzHXLr+WF92XtjBVMkjR+r39RtGbKndyIcKj5nralHCSzYH+6y2QBydj3AGJ5KwldDYJuCh18EeXH+Rl9udqrFQptwBcMYW7B0S4fTxQMZu+z6wNSWxvoDeCN3iR86UfcmVtivv1tsQSNqWWQPz+tmjwNrceqPcG9kzS8KM=
  file: "$LEOSAC_DEB"
  on:
    repo: islog/leosac
    tags: true
    all_branches: true
before_deploy:
    - cd "${TRAVIS_BUILD}/.."
    - mv leosac "leosac-${TRAVIS_TAG}"
    - pushd "leosac-${TRAVIS_TAG}"
    - bash scripts/travis_makepkg.sh
    - popd
    - LEOSAC_DEB="`find * -name leosac_*.deb`"
